---
apiVersion: v1
kind: Secret
metadata:
  name: environemt-file-frontend
type: Opaque
stringData:
  .env: |
    REACT_APP_SUPABASE_URL= <YOUR_SUPABASE_PROJECT_URL>
    REACT_APP_SUPABASE_ANON_KEY= <YOUR_SUPABASE_PROJECT_ANON_KEY>


---
apiVersion: v1
kind: Service
metadata:
  name: kubetweets-frontend-svc
spec:
  selector:
    app: kubetweets-f
  ports:
  - port: 3000
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kubetweets-frontend-svc
            port:
              number: 3000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetweets-frontend
spec:
  selector:
    matchLabels:
      app: kubetweets-f
  template:
    metadata:
      labels:
        app: kubetweets-f
    spec:
      containers:
      - name: kubetweets-f
        image: abcd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: env
          readOnly: true
          mountPath: "/app"
        ports:
        - containerPort: 3000
      volumes:
      - name: env
        secret:
          secretName: environemt-file-frontend